### ISSUE TITLE
How can I get the latency report

### ISSUE THREAD

**Issue by ericnie2015** [ihcsim/linkerd2-benchmark#1]
Hello, Expert:
   How can I get the latency report like your folder store at linkerd2-benchmark/reports/gke/charts/latency/?
I am interesting about that .
  Thank you a lot!

**Comment by ihcsim** [comment]
I don't remember. I may have created the subfolders manually. fortio has a `-data-dir` option that let you specify where to write the reports to.

**Comment by ericnie2015** [comment]
thank you for your reply, happy new year, my friend!
